### ISSUE TITLE
Configurable NodePort for Embedded Cluster

### ISSUE THREAD

**Issue by marccampbell** [slackernews/slackernews#78]
The Open SlackerNews app today needs to be able to support EC and Helm installs.

We have this right now:

```
  ports:
    - serviceName: slackernews
      servicePort: 443
      localPort: 443
      applicationUrl: "http://slackernews"
```

The localPort value needs to be more dynamic. We allow the user to specify the NodePort in the config. That value should be used. Or if a load balancer type is used, we need to read that address and have this here.
